global:
  message: Customer service prod environment message.
server:
  port: 8083
message: Just a message from prod.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cust_prod
    username: Artyomlbch
    password: Artyomlbch213853
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
