global:
  message: Order service dev environment message.
server:
  port: 8084
message: Just a message from order dev.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_dev
    username: postgres
    password: Artyomlbch213853
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
