global:
  message: Order service dev environment message.
server:
  port: 8084
message: Just a message from order dev.
spring:
  datasource:
    url: jdbc:h2:mem:order_master
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
